### ISSUE TITLE
Bug: BallotLab has no scan solution

### ISSUE THREAD

**Issue by brianolson** [TrustTheVote-Project/BallotLab#115]
[BallotStudio](https://github.com/TrustTheVote-Project/BallotStudio) already existed as a combined render-scan solution for printing ballots and scanning them to count marked bubbles. BallotLab seems to lack any scan solution.

**Comment by trustthevote** [comment]
Very good point! Now that we used BallotLab to meet the wacky specific requirements for the MarkIt project, there is now a potentially cool bit of assessment and planning to do on two fronts, to chart a course to 
(1) a standalone implementation of the ballot scanning functionality, that can 
a) re-use Ion's code for ingesting Cliff's current format/profile EDF for definitions of ballot style, and 
b) use that to assign meaning to mark zones, and
c) generate a current format/profile cast-vote-record
(2) determine what BallotStudio functionality got left behind in the rush for MarkIt, and 
a) how to combine
b) while specifying the start of a ballot-layout configuration that expresses a variety of jurisdiction specific directives
This gets very interesting!

**Comment by brianolson** [comment]
BallotStudio scan code defines [a json format for bubble info](https://github.com/brianolson/ballotstudio/blob/master/scan/scan.go#L1242-L1281).
It looks like BallotLab's rendering is also the same underlying `reportlab` pdf utility library, so the same pt based page coordinates might Just Work.

**Comment by stratofax** [comment]
Hey, @brianolson thanks for posting! Both you and @trustthevote have a much better grasp on the intricacies of ballot scanning.

You are 100%, BallotLab does not have any ballot scanning capabilities. Therefore, the lack of said feature is not exactly a "bug" -- we reserve that term for existing code that doesn't work as expected. Since the feature you're describing is pehaps an enhancement, or perhaps, as @trustthevote notes, even beyond the scope of BallotLab, it really makes more sense to move this to the Discussion area on this repo. 

To help with that, I've created a new discussion, [New Features for BallotLab · Discussion #116 · TrustTheVote-Project/BallotLab](https://github.com/TrustTheVote-Project/BallotLab/discussions/116), and copied over the text of your original issue, your comment, and @trustthevote 's reply, here: https://github.com/TrustTheVote-Project/BallotLab/discussions/116#discussioncomment-3684069

It would be great if you and the rest of the team could pursue this discussion on that thread. I'm going to close this issue thread, since (as noted) it's not really a "bug" and generally better suited for our discussion board.

Again, thanks for your input and your valuable expertise on ballot scanning!
